opt_out_usage
default_platform(:ios)

platform :ios do
  before_each do
    if is_ci
      setup_ci # creates MATCH_KEYCHAIN_NAME on CI
      ensure_env_vars(
        env_vars: ['APPSTORE_CERTIFICATE_PASSWORD']
      )
      import_certificate(
        certificate_path: 'keys/Distribution.p12',
        certificate_password: ENV['APPSTORE_CERTIFICATE_PASSWORD'],
        keychain_name: ENV['MATCH_KEYCHAIN_NAME'],
        keychain_password: ENV['MATCH_KEYCHAIN_PASSWORD'],
      )
      get_provisioning_profile(
        api_key_path: 'keys/appstore.json',
        app_identifier: 'app.organicmaps',
        provisioning_name: 'CarPlay AppStore',
        ignore_profiles_with_different_name: true,
        adhoc: false,
        readonly: true,
        filename: 'keys/CarPlay_AppStore.mobileprovision'
      )
      install_provisioning_profile(
        path: 'keys/CarPlay_AppStore.mobileprovision'
      )
    end
  end

  private_lane :generate_version do
    timestamp = sh("git log -1 --format=%ct").strip
    date_of_last_commit = sh("date -u -r " + timestamp + " '+%Y-%m-%d'").strip
    build_number = sh("git rev-list --count --after=\"" + date_of_last_commit + "T00:00:00Z\" HEAD").strip
    version_number = date_of_last_commit.gsub!("-", ".")
    lane_context[SharedValues::VERSION_NUMBER] = version_number
    lane_context[SharedValues::BUILD_NUMBER] = build_number
  end

  private_lane :generate_testflight_changelog do
    # 4000 chars max, one line is 80 chars = 50 lines max
    changelog = sh('
      git log --pretty=\'- %s\' $(git describe --tags --abbrev=0)..HEAD|
      grep -ivE "\[android\]|\[tools\]|\[string\]\[generator\]"|
      tail -n 49
    ')
    lane_context[SharedValues::FL_CHANGELOG] = changelog
  end
 
  lane :upload_testflight do
    generate_version
    generate_testflight_changelog
    build_app(
      workspace: 'omim.xcworkspace',
      scheme: 'OMaps',
      configuration: 'AppStore',
      clean: false,
      include_symbols: true,
      include_bitcode: true,
      export_method: 'app-store',
      export_options: {
        provisioningProfiles: {
          'app.organicmaps' => 'CarPlay AppStore'
        }
      },
      skip_profile_detection: false,
      output_directory: 'build',
      xcargs: 'MARKETING_VERSION=' + lane_context[SharedValues::VERSION_NUMBER] + ' ' +
              'CURRENT_PROJECT_VERSION=' + lane_context[SharedValues::BUILD_NUMBER] + ' '
    )
    upload_to_testflight(
      beta_app_feedback_email: 'testflight@organicmaps.app',
      notify_external_testers: false,
      changelog: lane_context[SharedValues::FL_CHANGELOG]
    )
  end
end
